// This file is automatically generated. Do not edit it directly.
// NOTE: This project is migrating from Supabase to self-hosted API
// Supabase client is kept for backward compatibility during migration
// ⚠️ Components should migrate to use apiClient from @/lib/api-client instead

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Create Supabase client only if env vars are provided
// If not provided, create a mock client that throws helpful errors
let supabaseClient: ReturnType<typeof createClient<Database>> | null = null;

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
} else {
  // Create a mock client that throws helpful errors
  console.warn('⚠️ Supabase env vars not set. Components should use apiClient from @/lib/api-client instead.');
  
  // Create a minimal mock to prevent crashes
  supabaseClient = createClient<Database>(
    'https://placeholder.supabase.co',
    'placeholder-key',
    {
      auth: {
        storage: localStorage,
        persistSession: false,
        autoRefreshToken: false,
      }
    }
  );
}

export const supabase = supabaseClient;